name = "errstat"
version = "0.2.0"
license = "MIT"
author = "Tomohiro Degawa"
maintainer = "@degawa/errstat"
copyright = "Copyright 2022-2023, Tomohiro Degawa"

[build]
auto-executables = true
auto-tests = true
auto-examples = true

[install]
library = true
